name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: "ðŸ§¹ Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run formatting
        run: bun run format

  lint:
    name: "ðŸ§¹ Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run linting
        run: bun run lint

  typecheck:
    name: "ðŸ”Ž Typecheck"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Run type checking
        run: bun run typecheck
