name: Test PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: "ðŸ”’ Saltman Action (PR)"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Saltman Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          provider: openai
          api-key: ${{ secrets.OPENAI_API_KEY }}
          post-comment-when-no-issues: true
          ignore-patterns: |
            **/*.md
            package.json
            bun.lockb
